name: build_and_push_image
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Super-Linter"]
    types:
      - completed
      - requested

env: # Global environment variables
  PACKAGE_NAME: syft
  PACKAGE_SOURCE_MAIN: "https://push.chocolatey.org/"
  PACKAGE_SOURCE_TEST: "https://www.myget.org/F/public-choco-dev/api/v2/package"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]

    steps:
      # Common Steps for All Branches
      - name: Checkout
        uses: actions/checkout@v4
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack
      - name: Choco install Grype
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ${{ env.PACKAGE_NAME }} -y -s .

      - name: Run version check
        run: |
           ${{ env.PACKAGE_NAME }} version
        shell: powershell

      # Branch-Specific Steps

      # Only runs on main or master branches
      - name: Push to Chocolatey on main or master
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push --source https://push.chocolatey.org/ -k=${{ secrets.CHOCO_API_KEY }}

      # Only runs on the test branch
      - name: Push to MyGet on test branch
        if: github.ref == 'refs/heads/test'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push --source https://www.myget.org/F/public-choco-dev/api/v2/package -k=${{ secrets.MYGET_API_KEY }}
