name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
      - master

env: # Global environment variables
  PACKAGE_NAME: syft # Defining the package name as an environment variable
  PACKAGE_SOURCE_MAIN: "https://push.chocolatey.org/"
  PACKAGE_SOURCE_TEST: "https://www.myget.org/F/public-choco-dev/api/v2/package"

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@latest
        env:
          DEFAULT_BRANCH: main,test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [super-lint]  # This ensures super-lint runs first
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack

      - name: Choco install Grype
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ${{ env.PACKAGE_NAME }} -y -s .

      - name: Run version check
        run: |
          ${{ env.PACKAGE_NAME }} version
        shell: powershell

      # Branch-Specific Steps
      - name: Push to Chocolatey on main or master
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || matrix.os == 'windows-2022'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push --source https://push.chocolatey.org/ -k=${{ secrets.CHOCO_API_KEY }}

      - name: Push to MyGet on test branch
        if: github.ref == 'refs/heads/test'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push --source https://www.myget.org/F/public-choco-dev/api/v2/package -k=${{ secrets.MYGET_API_KEY }}